version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: wave_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./wave_db:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - shared-network

  wave-app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - shared-network
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/wave/app
      - ./public:/usr/src/wave/public

networks:
  shared-network:

